### ISSUE TITLE
Deepl API Key Invalid

### ISSUE THREAD

**Issue by Vandree1977** [Meneltamar/fvtt-comprehend-languages#23]
hello i use the deepl api for foundry v10 after i updated my account it keeps telling me that my api token is invalid but my token now replaced several times always the same problem

**Comment by Meneltamar** [comment]
Did you get a Pro-Subscription for DeepL? If yes, the module currently does
not support Pro accounts. It should be an easy addition, but I won't be
able to work on it until tomorrow.

Am So., 26. März 2023 um 18:10 Uhr schrieb Vandree1977 <
***@***.***>:

**Comment by Meneltamar** [comment]
Now that I think about it, I don't think I am comfortable implementing the Pro API URL into the module, as I don't want to be responsible for people racking up charges, if anything goes wrong. 

I can show you where you have to make a change in the files, to get it to work.

Could you confirm that you upgraded to an API Pro account?

**Comment by Vandree1977** [comment]
Yes I have performed an update

**Comment by Vandree1977** [comment]
I have updated to API Pro today

**Comment by Meneltamar** [comment]
Go into your modules folder.  

Under modules/comprehend-languages/scripts open the "main.js" file with any text editor. In line 503 (or search for "api-free"), replace the code like this:

```js
let response = await fetch("https://api-free.deepl.com/v2/translate?" + data, {
```

becomes
```js
let response = await fetch("https://api.deepl.com/v2/translate?" + data, {
```

Save the file, restart your world and it should work.

**Please note**:  
I do not take any responsibility for charges you receive on your DeepL Account due to errors in the module. I cannot guarantee that the translations always work and I know that the error handling in the module is not the best at the moment. This could mean that if you try to translate large JournalEntries that the translation completely fails but your account still gets charged. Changing this behavior (to at least have the parts of the translations that worked saved into Foundry) is on my list, but I won't be able to work on it soon. You will have to do this on your own responsibility.

**Comment by Meneltamar** [comment]
You will have to make this change again whenever the module is updated.

**Comment by Vandree1977** [comment]
Hello, I am playing on The Forge and somehow I don't have the option to change anything in the script. I cannot access the module. Can you help me?
